### ISSUE TITLE
没用起。。。

### ISSUE THREAD

**Issue by mfkwvf** [xuerhuo/phpjm_decode#1]
太高级了，可以指教吗？

**Comment by xuerhuo** [comment]
将加密文件置于同级目录下  加密文件修改为 core.php这个名字 然后访问一下解密php文件 @mfkwvf

**Comment by mfkwvf** [comment]
@xuerhuo 谢谢大神，我是这样执行的，可能是文件加密不是这个

**Comment by xuerhuo** [comment]
@mfkwvf  客气了
